export const productsData = [
  // Indian products
  {
    id: 1,
    name: "Aamras Mango Pulp",
    img: "https://images.unsplash.com/photo-1553279768-865429fd8b1b?w=400&q=80",
    culture: "hi",
    score_authenticity: 9.4,
    score_distance: 1.2,
    score_price: 3.50,
    store: "Patel Brothers Grocery",
    tags: ["Indian", "Sweet", "Pulp"],
    reviews: 124,
    keywords: ["mango", "aam", "आम", "pulp", "aamras", "आमरस", "sweet", "juice", "fruit"]
  },
  {
    id: 4,
    name: "MDH Garam Masala",
    img: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    culture: "hi",
    score_authenticity: 9.9,
    score_distance: 0.8,
    score_price: 2.10,
    store: "Spices of India",
    tags: ["Indian", "Spice", "Essential"],
    reviews: 540,
    keywords: ["masala", "मसाला", "garam", "गरम", "spice", "mdh", "mix", "powder"]
  },
  {
    id: 7,
    name: "Haldiram's Aloo Bhujia",
    img: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80",
    culture: "hi",
    score_authenticity: 9.2,
    score_distance: 1.5,
    score_price: 2.80,
    store: "Patel Brothers Grocery",
    tags: ["Indian", "Snack", "Savoury"],
    reviews: 312,
    keywords: ["bhujia", "भुजिया", "aloo", "आलू", "haldiram", "snack", "namkeen", "नमकीन", "crispy"]
  },
  {
    id: 8,
    name: "Tata Gold Tea",
    img: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    culture: "hi",
    score_authenticity: 9.7,
    score_distance: 0.8,
    score_price: 4.50,
    store: "Spices of India",
    tags: ["Indian", "Tea", "Beverage"],
    reviews: 428,
    keywords: ["chai", "चाय", "tea", "tata", "gold", "beverage", "drink"]
  },
  {
    id: 9,
    name: "Parle-G Biscuits",
    img: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&q=80",
    culture: "hi",
    score_authenticity: 9.8,
    score_distance: 1.0,
    score_price: 1.20,
    store: "Patel Brothers Grocery",
    tags: ["Indian", "Biscuit", "Classic"],
    reviews: 670,
    keywords: ["parle", "biscuit", "बिस्कुट", "cookie", "glucose", "snack", "tea time"]
  },

  // Arabic products
  {
    id: 2,
    name: "Almarai Laban",
    img: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&q=80",
    culture: "ar",
    score_authenticity: 9.8,
    score_distance: 2.5,
    score_price: 1.99,
    store: "Amanah Supermarket",
    tags: ["Arabic", "Dairy", "Drink"],
    reviews: 310,
    keywords: ["laban", "لبن", "almarai", "المراعي", "milk", "حليب", "dairy", "drink", "yogurt"]
  },
  {
    id: 6,
    name: "Zaatar Mix (Al Wadi)",
    img: "https://plus.unsplash.com/premium_photo-1664301524345-90a694774519?w=400&q=80",
    culture: "ar",
    score_authenticity: 9.1,
    score_distance: 1.5,
    score_price: 3.00,
    store: "Beirut Bazaar",
    tags: ["Arabic", "Spice", "Breakfast"],
    reviews: 175,
    keywords: ["zaatar", "زعتر", "thyme", "spice", "breakfast", "فطور", "mix", "al wadi"]
  },
  {
    id: 10,
    name: "Al Rabih Tahini",
    img: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80",
    culture: "ar",
    score_authenticity: 9.5,
    score_distance: 2.0,
    score_price: 3.50,
    store: "Amanah Supermarket",
    tags: ["Arabic", "Condiment", "Sesame"],
    reviews: 245,
    keywords: ["tahini", "طحينة", "sesame", "سمسم", "hummus", "حمص", "dip", "paste"]
  },
  {
    id: 11,
    name: "Medjool Dates (Badia)",
    img: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=400&q=80",
    culture: "ar",
    score_authenticity: 9.6,
    score_distance: 1.8,
    score_price: 6.50,
    store: "Beirut Bazaar",
    tags: ["Arabic", "Fruit", "Sweet"],
    reviews: 390,
    keywords: ["dates", "تمر", "medjool", "مجدول", "sweet", "حلو", "fruit", "فاكهة", "ramadan"]
  },
  {
    id: 12,
    name: "Lebanese Flatbread",
    img: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
    culture: "ar",
    score_authenticity: 8.8,
    score_distance: 1.2,
    score_price: 2.20,
    store: "Amanah Supermarket",
    tags: ["Arabic", "Bread", "Staple"],
    reviews: 520,
    keywords: ["bread", "خبز", "flatbread", "pita", "بيتا", "lebanese", "لبناني", "manakish"]
  },

  // Brazilian / Portuguese products
  {
    id: 3,
    name: "Pão de Queijo Mix (Yoki)",
    img: "https://images.unsplash.com/photo-1598142980838-89fa2d21cc41?w=400&q=80",
    culture: "pt",
    score_authenticity: 8.9,
    score_distance: 5.1,
    score_price: 4.20,
    store: "Brasil Foods UK",
    tags: ["Brazilian", "Baking", "Cheese Bread"],
    reviews: 89,
    keywords: ["pão", "queijo", "cheese", "bread", "yoki", "baking", "brazilian"]
  },
  {
    id: 5,
    name: "Guaraná Antarctica",
    img: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&q=80",
    culture: "pt",
    score_authenticity: 9.6,
    score_distance: 3.0,
    score_price: 1.50,
    store: "Latin Grocers",
    tags: ["Brazilian", "Drink", "Soda"],
    reviews: 212,
    keywords: ["guaraná", "guarana", "antarctica", "soda", "refrigerante", "drink", "bebida"]
  },
  {
    id: 13,
    name: "Farofa Pronta (Yoki)",
    img: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400&q=80",
    culture: "pt",
    score_authenticity: 9.3,
    score_distance: 5.1,
    score_price: 3.80,
    store: "Brasil Foods UK",
    tags: ["Brazilian", "Side Dish", "Cassava"],
    reviews: 145,
    keywords: ["farofa", "mandioca", "cassava", "yoki", "farinha", "side dish", "feijoada"]
  },
  {
    id: 14,
    name: "Café Pilão Torrado",
    img: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    culture: "pt",
    score_authenticity: 9.7,
    score_distance: 4.2,
    score_price: 5.50,
    store: "Latin Grocers",
    tags: ["Brazilian", "Coffee", "Beverage"],
    reviews: 334,
    keywords: ["café", "cafe", "coffee", "pilão", "pilao", "torrado", "roasted", "bebida"]
  },
  {
    id: 15,
    name: "Goiabada Cascão",
    img: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=400&q=80",
    culture: "pt",
    score_authenticity: 9.0,
    score_distance: 5.1,
    score_price: 3.20,
    store: "Brasil Foods UK",
    tags: ["Brazilian", "Sweet", "Guava"],
    reviews: 98,
    keywords: ["goiabada", "goiaba", "guava", "doce", "sweet", "sobremesa", "dessert", "cascão"]
  }
];
